version: '3'

services:
  db:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    hostname: web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - db
